apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  source:
    chart: helm-guestbook
    repoURL: https://github.com/MarkRamm-harness/gitops-demo
    targetRevision: 1.16.1
    helm:
      releaseName: helm-guestbook
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helm-guestbook-flux
