apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MarkRamm-harness/gitops-demo
    path: podinfo/podinfo
    targetRevision: main
    helm:
      valueFiles:
        - podinfo-test.yaml
  destination:
    server: https://35.224.207.9
    namespace: pod-test
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=undefined
      - CreateNamespace=true
      - Validate=true
      - PruneLast=false
      - ApplyOutOfSyncOnly=false
      - FluxSubsystem=false
      - AutoCreateFluxResources=false
      - Replace=false
      - retry=false
