source:
  repoURL: https://github.com/MarkRamm-harness/gitops-demo
  path: platform
  targetRevision: main
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: platform
syncPolicy:
  syncOptions:
    - PrunePropagationPolicy=undefined
    - CreateNamespace=true  # Set to true to enable automatic namespace creation
    - Validate=true
    - PruneLast=false
    - ApplyOutOfSyncOnly=false
    - FluxSubsystem=false
    - AutoCreateFluxResources=false
    - Replace=false
    - retry=false
