apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: flux
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: gitops-agent-secret
    app.kubernetes.io/part-of: argocd
  name: fluxargo-agent
  namespace: flux
type: Opaque
stringData:
  GITOPS_AGENT_TOKEN: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURjdzNTejlOSW9BWEtNCk9TVm05eW9jdXVRRWdQaDBjYVdVTHhyUXdJaEx6VnNGTTdSRU9YNHhwdUlTSzZpYks1ZTdBYVpiYlYzVFRWckgKVUlSKzlLKzZHM3AwL2xrY09lQnZvSnNrbSs1Z25LNG9ZYWZzZ1N5U0p1UjdRNGNhUEQ2UVA1L0NhTGNhY0lUQgo1SGwxaWlLVGgrTDAyN05weGcxVXdaaHR4T0FwaTE3Wk4rdE82Syt4azk4M1pmOS90MGNGV3MrL21jQjRtRHU1CmxIQ0lXL0ZLSWlRWVljUTZublkrTWpNd0sxNzBQak1Kamk5SmRsV2J3SjNtbUJRMDcrdWhROVZhRWQxc0UxSUsKdmZ4ZHZ5UkpLcGUxb2RUOTMwa3M3dm1UTHJ5YTVxYTlVMExXSGhLbEdSamRiM2srM1k2L1B1dUl4UXdSaUFwMwoybmgyUTBJbkFnTUJBQUVDZ2dFQkFKdHc0RDVKbHFQbWlRSWt4cW9lUkQrZ2RDYWJyTlZJby82WHdEaldKK0cvCndXUURTTjEwNGQ4U0UwSWFEWWpjZytSL3YrUEdPUGNzRTB3ZDdIejd5ck91MzJWN0pjRlRHeTFlRjM4S2NDa0UKaVRnVHNzbzdGZWYraklnaVB3R0JBOGhMbERDdHpLZElMS0hkUG93OWJDVVcyLzN1cUFCRkhHUGVRSGFoMWZoSgpRekxiZTlyNlZ5d252MVdYQ3FKTTZmbG1pcEU0cEhMSVp5dEtIWkw2Y25USm1INlN0YXBDZkp3ZjFzc1hRMncyCkx3YjE4Z0pVTUtJU1VwT0VkREw3RFNvWCtKS293V2UzQ0ZkMVFLVWo0eUg2eER2bERHNCtwZ3VCMk5haEFvSk0KMUtva2FYbXZXV3lHYVhUNVFJcVYrT2ZHTHUreTR1OVVnVTI0YUJtdm9Ka0NnWUVBM2JtU3I3bXlqeUFJQVBBbwpkOElTM1FzVXFKcThkS0JWT0dKMllSYm9hdDVTbnpDZVJ1TS8rM3ZKNG1pMHgraUlvOXF6QmN4ZlRNWE5YSGNhClJtR2N2ZzBlVWx1RmdFNVNSeFdQWTRwTDgzdjFwVnFmVXhJQTNsM0JjejREaGJmdkY3a2dvTlR1K2ZkTDkrbnUKVFlCQjRya05uZGt3NHMvcG5FZHFJdVVkbE0wQ2dZRUEvdVBXVGRPbjFTazZMN05RUjhNeFJsMXhRTjdCc1U0SwplSW10aCtyS2hhMHJDMGFsTkFjNFhKN3BIaDRmdjZGYkdpelFqMzVEMXBQUTQ2NEZERkxrd1ZZTXp6dTRwcUhUCmttaU1uL2dpVjVCM0hRQzJuN1NiZ1NOV1pnTzN4c2ErYkR0MnZwTXNaN2ZXaWFzQ0tmRkVZWnBSQlgwRWlicnEKNUNwK1JXbFdrc01DZ1lCZkJpUVdpWmc3L0xkUlo1dUFUNzF6M0ViYlI0MlMwaEFUM1Nic3p6dUdhWWV4VDgzVgpoWmtyTjA4N2FESnFKbjlBOGY2ZGNvdzVRK0NTU3owSWd0Y0JJSEFwVGEzMllocWkrbHQ4aG8yc2FTaksxLzdHClJFWDVCdWRjYzJ4aEI0WkJmWWE5UnVTd1hrckJraEVlUitSMHZXaFhpUGlKakIrTGFaUFVKcXM1MVFLQmdRRDEKenY5Qyt0VW1LcVlramtiampnZ2RGY3c4aFJaQ1NVS3IwQXA3d3lBZ0hrb2VpN2lTSGt4cWRnM1dyN0pxZWMrRAp4S2cxV2MxT1NDcnhCMGR6QlJYNnBXT2hEclVhYllHOTlmbDM1RElxUS9XN0VJOE9JWHk5NHpoVkZVekw4NnA4CmNqUW53WUxYVzJFWVRzUzljaUZDQnpJUG11c2ZjQlZLaVBoUk5DNzdSUUtCZ0VYbk5GQUhzNTN6TnJEMjVLekwKa3o5ZHAydnNZRVE0ekZ1Zi8zZGxaMmFRakhuYm03WUUvdXhNcFdVZjJzSnYzZGMwME1yVC9BUWhQLzZlZjZXRwpod09VdmZkNCtkalNZSWhFL2preEhuUEwyNHVnMHFTazllNXJCY2JqblYwbmFlRUlnbmZZTFZHUThqMFowRnVUCldBditRVXh3Q2daMXJJVEpHbUMvOEwyYgotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---